### ISSUE TITLE
Audio Generation

### ISSUE THREAD

**Issue by ikou-austin** [NXTProduct/TUNet#1]
Hi, I am trying to reproduce your code, training and validation are working fine, but when I try to use test mode for audio generation, I found that you did not use Chebyshev filter when extracting the data as in training and validation, but directly patch some zeros after the original data, which means that the input signal of the model is no longer only low-frequency signal, thus, the output will not be band extension.

How do I modify the test function if I need to band extend the low-frequency part of the original audio file?

Thank you！

**Comment by anhnv125** [comment]
In testing phase, I would assume there is only low-rate data (as opposed to the evaluation phase where you may obtain high-rate audios for calculating metrics), thus low-pass filtering is not applied on test audios. However if you want to downsample your audios to 8 kHz, you could use librosa's `resample()` or scipy's `decimate()` after loading the audio, then resample it back to 16 kHz (see `dataset.py` for example):
https://github.com/NXTProduct/TUNet/blob/118e2c61cddd2f9d2d9f3ac5a095c22f7d762a12/dataset.py#L79-L94
Zero-padding only makes audio length divisible to `stride` so that the consequent `frame()` function works correctly.

**Comment by ikou-austin** [comment]
Thank you for your help! now I can reproduce your code.
But I got a new question now: is it possible to directly input a power spectrogram into the model, instead of a raw waveform for band extension tasks? Or, do you know any 
spectrogram-based band extension works?

**Comment by anhnv125** [comment]
Yes, you can use spectrograms as the model input with just a little modification on the input and output layers. There are several studies that utilize spectrogram (see [here](https://hal.archives-ouvertes.fr/hal-02473457/document)) or both waveform signal and time-frequency representation (see [here](https://teckyianlim.me/audio-sr/res/3828.pdf)).

**Comment by ikou-austin** [comment]
Many thanks for your reply!
